title: "Arbiteg"
email: info@arbiteg.com
phone: +1(818)519-2058
description: >- # this means to ignore newlines until "baseurl:"
  Join Arbiteg, join fair future.
baseurl: "" # the subpath of your site, e.g. /blog

# url: "https://www.arbiteg.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://arbiteg-com.herokuapp.com"

facebook_username: arbitegInc
instagram_username: arbitegInc

# Production
google_analytics: UA-81206382-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

header_pages:
  - mission.md
  - farmers.md
  - pricing.md
  - team.html

collections:
  members:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
